spring.application.name=libreria

server.port=1501
spring.datasource.url=jdbc:mysql://localhost:3306/libreria?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sistema5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
